# -*- mode: python ; coding: utf-8 -*-
# Solid 酒店 PMS — PyInstaller 目录版（启动快，避免单文件每次解压）
from PyInstaller.utils.hooks import collect_dynamic_libs

try:
    sqlcipher_binaries = collect_dynamic_libs('sqlcipher3')
except Exception:
    sqlcipher_binaries = []

a = Analysis(
    ['app_main.py'],
    pathex=[],
    binaries=sqlcipher_binaries,
    datas=[
        ('themes', 'themes'),
        ('translations', 'translations'),
        ('assets', 'assets'),
        ('lock_adapters/rfl_bridge_32.py', 'lock_adapters'),
        # __pycache__ .pyc removed (unstable; .py source is already imported)
        ('lock_adapters/profile', 'lock_adapters/profile'),
        ('solid_ui_v2/compiled', 'solid_ui_v2/compiled'),
    ],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtPrintSupport',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'ntplib',
        'psutil',
        'screeninfo',
        'qrcode',
        'qrcode.image.pil',
        'qrcode.image.svg',
        'PIL',
        'PIL.Image',
        'cryptography',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.backends',
        'sqlcipher3',
        'reportlab',
        'app_main',
        'brand_config',
        'database',
        'db_schema',
        'db_migration',
        'secure_db',
        'i18n',
        'event_bus',
        'single_instance',
        'startup_splash',
        'main_window',
        'main_window_impl',
        'workspace_dock',
        'sound_helper',
        'production_defaults',
        'license_manager',
        'vendor_activation_screen',
        'vendor_gate',
        'vendor_lockdown',
        'permission_system',
        'permission_legacy_map',
        'theme_palette',
        'design_tokens',
        'theme_motion',
        'motion_gate',
        'money_utils',
        'nav_manifest',
        'shop_icon_pack',
        '_generate_themes',
        'audit_tab_widget',
        'ledger_format',
        'ui_helpers',
        'ui',
        'ui.tokens',
        'ui.tokens.colors',
        'ui.tokens.spacing',
        'ui.tokens.typography',
        'ui.layout',
        'ui.layout.frontdesk',
        'ui.components',
        'ui.components.toast',
        'ui.branding',
        'ui.branding.brand',
        'ui.emptystate',
        'overlay_widgets',
        'debug_panel',
        'command_palette',
        'deploy_paths',
        'runtime_deps',
        'mdb_import_backend',
        'legacy_preflight',
        'construct',
        'lock_adapters.cardlock_auto',
        'lock_adapters.generic_adapter',
        'lock_adapters.seq_manager',
        'lock_adapters.profile',
        'lock_adapters.profile.brand_analyzer',
        'lock_adapters.profile.payload_factory',
        'lock_adapters.middleware',
        'lock_adapters.middleware.config_extractor',
        'lock_adapters.middleware.verifier',
        'overview_data',
        # ── 门户/前台 ──
        'frontdesk_flow_strip',
        'frontdesk_layers',
        'frontdesk_ui',
        'ui_surface',
        'ui_probe',
        'frontdesk_ledger_strip',
        'shop_frontdesk',
        'card_data',
        'card_system',
        'card_ritual_dialog',
        'card_sniffer',
        'cardlock_frontdesk',
        'batch_create_dialog',
        'usb_lock_scanner',
        'usb_lock_migrate_dialog',
        # 'lock_diag_page',  # 已删除
        'lock_issue_service',
        'lock_legacy_bridge',
        # ── 选项卡（tabs/ 无 __init__.py，需要显式列出） ──
        'tabs',
        'tabs.frontdesk',
        'tabs.frontdesk.checkin_tab',
        'tabs.frontdesk.shift_dock',
        'tabs.frontdesk.checkout',
        'tabs.frontdesk.guest_info',
        'tabs.frontdesk.hub_widget',
        'tabs.frontdesk.payment',
        'tabs.frontdesk.payment_v4',
        'tabs.frontdesk.refund',
        'tabs.frontdesk.refunds_tab',
        'tabs.frontdesk.bill_detail_dialog',
        'tabs.frontdesk.roster_tab',
        'tabs.frontdesk.service_tab',
        'tabs.frontdesk.shift_tab',
        'tabs.frontdesk.shop_tab',
        'tabs.frontdesk.team',
        'tabs.frontdesk.borrow_items',
        'smart_header',
        'enhanced_status_bar',
        'mini_tab_strip',
        'tabs.finance_tab',
        'tabs._shared',
        'tabs.frontdesk._shared',
        'tabs.guest_list_tab',
        'tabs.hotel_overview_tab_v4',
        'tabs.inventory_tab',
        'tabs.staff_tab',
        'tabs.member_tab',
        'tabs.pricing_tab',
        'tabs.night_audit_tab',
        'tabs.energy_audit_group',
        'tabs.system_console_tab',
        'tabs.vendor_console_tab',
        'tabs.cloud_config_dialog',
        # ── 门卡系统拆分模块 ──
        'tabs.card_system',
        'tabs.card_system._shared',
        'tabs.card_system.card_driver',
        'tabs.card_system.card_service',
        'tabs.card_system.card_issue',
        'tabs.card_system.card_settings',
        'tabs.card_system.card_open_history',
        'tabs.card_system.card_system_tab',
        'transactions.checkin',
        'transactions.checkout',
        'transactions.extend_stay',
        'transactions.lost_card',
        'transactions.room_change',
        'lock_adapters',
        'lock_adapters.base',
        'lock_adapters.prousb_v9',
        'lock_adapters.prousb_v10',
        'lock_adapters.prousb_v11',
        'lock_adapters.bridge_client',
        'lock_adapters.rfl_bridge_32',
        'lock_adapters.card_corpus',
        'lock_adapters.hardware_support',
        # 注意：其他品牌（爱迪尔/必达等）由 GenericLockAdapter + Profile 覆盖
        'lock_deploy',
        'lock_deploy.scanner',
        'lock_deploy.importer',
        'lock_deploy.live_mdb',
        'lock_deploy.diag',
        'lock_deploy.diag_tools',
        'lock_deploy.wizard_page',
        'lock_deploy.dll_probe',
        'lock_deploy.profile_merger',
        'lock_deploy.handover_importer',
        'lock_deploy.cloud_handover_pull',
        # ── BridgeCore 中间层（PMS 端仅 panic_recovery + config） ──
        'bridgecore',
        'bridgecore.config',
        'bridgecore.panic_recovery',
        'telegram_shadow',
        'telegram_handlers',
        'telegram_messages',
        'telegram_bot_config',
        'heartbeat_service',
        'local_adapter',
        'health_monitor',
        'audit_engine',
        'task_queue',
        'energy_scheduler',
        'energy_audit_engine',
        'energy_entry_page',
        'stocktake_scheduler',
        'inventory_audit_engine',
        'inventory_baseline',
        'inventory_diff_page',
        'item_dictionary_page',
        'ota_connector',
        'telegram_notify',
        'input_validation',
        'backup_service',
        'offline_queue',
        'remote_diag',
        'auto_updater',
        'install_checks',
        'pricing_engine',
        'room_matrix',
        'unified_room_page',
        'housekeeping_panel',
        'timeline_view',
        'shop_inventory',
        'power_controller_config',
        'setup_wizard',
        'role_navigation',
        'role_permissions_page',
        'role_ui',
        'brand_assets',
        'report_engine',
        'legacy_migration_guide',
        'migration_guide_panel',
        'legacy_flow_guide',
        'legacy_migration',
        'legacy_migration.schema_analyzer',
        'legacy_migration.cardlock_scanner',
        'legacy_migration.data_importer',
        'legacy_postimport',
        'legacy_takeover_hub',
        'legacy_lock_cards_page',
        'one_click_migration',
        'reconciliation_checks',
        'reconciliation_service',
        'design_tokens_v4',
        'frontdesk_ui_v4',
        'brand_config_v4',
        'components',
        'components.button_optimized',
        'services.payment_complete',
        'services.bill_detail',
        'services.exchange_rate',
        'services.booking_link',
        'services.ota_reserve',
        'services.event_queue',
        'services.reconciliation_report',
        'services.bootstrap',
        'services.card_service',
        'services.checkout_service',
        'services.report_service',
        'transactions.refund',
        'transactions.deposit',
        'takeover_report',
        'data_import_service',
        'integrity_report',
        'manufacturer_comm',
        'cloud_security',
        'qr_code_service',
        'live_qr_client',
        'room_standee_renderer',
        'crypto_utils',
        'usb_driver_helper',
        'initial_stocktake_wizard',
        'consumable_standards',
        'shop_catalog',
        'shop_assets',
        'telemetry',
        # ── Solid UI v2 设计系统 ──
        'solid_ui_v2',
        'solid_ui_v2.tokens',
        'solid_ui_v2.tokens.spacing',
        'solid_ui_v2.tokens.typography',
        'solid_ui_v2.tokens.radius',
        'solid_ui_v2.tokens.shadow',
        'solid_ui_v2.tokens.motion',
        'solid_ui_v2.tokens.layout',
        'solid_ui_v2.themes',
        'solid_ui_v2.themes._schema',
        'solid_ui_v2.themes.mist',
        'solid_ui_v2.themes.shade',
        'solid_ui_v2.themes.glow',
        'solid_ui_v2.themes.ink',
        'solid_ui_v2.runtime',
        'solid_ui_v2.runtime._resolver',
        'solid_ui_v2.runtime._aliases',
        'solid_ui_v2.runtime.color_utils',
        'solid_ui_v2.runtime.expand',
        'solid_ui_v2.runtime.contrast',
        'solid_ui_v2.runtime.api',
        'solid_ui_v2.qss',
        'solid_ui_v2.qss.compiler',
        'solid_ui_v2.qss._static_tokens',
        'solid_ui_v2.qss._patches',
        'solid_ui_v2.qss.patches',
        'solid_ui_v2.qss.patches.01_font_family',
        'solid_ui_v2.qss.patches.02_navbtn_active_accent',
        'solid_ui_v2.qss.patches.03_kpi_card_unify',
        'solid_ui_v2.qss.patches.04_header_height',
        'solid_ui_v2.qss.patches.05_kpi_value_size',
        'solid_ui_v2.qss.patches.06_sidebar_theme_follow',
        'solid_ui_v2.qss.patches.07_no_concat_hack',
        'sqlite3',
        '_sqlite3',
        'hashlib',
        'uuid',
        'json',
        'csv',
        'datetime',
        'glob',
        'shutil',
        'struct',
        'zlib',
        'io',
        'codecs',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['python-telegram-bot', 'telegram', 'numpy', 'lxml',
              'tkinter', 'matplotlib', 'IPython', 'jupyter', 'setuptools', 'pip', 'unittest',
              'PySide6.QtQuick', 'PySide6.QtQml', 'PySide6.Qt3DCore', 'PySide6.Qt3DRender',
              'PySide6.Qt3DInput', 'PySide6.Qt3DAnimation', 'PySide6.Qt3DExtras',
              'PySide6.QtPdf', 'PySide6.QtPdfWidgets', 'PySide6.QtDataVisualization',
              'PySide6.QtSensors', 'PySide6.QtBluetooth', 'PySide6.QtNfc',
              'PySide6.QtSerialPort', 'PySide6.QtPositioning', 'PySide6.QtLocation',
              'PySide6.QtWebEngineWidgets', 'PySide6.QtWebEngineCore',
              'PySide6.QtWebChannel', 'PySide6.QtWebSockets',
              'PySide6.QtMultimedia', 'PySide6.QtMultimediaWidgets',
              'PySide6.QtSpatialAudio', 'PySide6.QtHelp',
              'PySide6.QtTest', 'PySide6.QtConcurrent', 'PySide6.QtSql',
              'scipy', 'pandas', 'notebook', 'jupyterlab', 'sympy', 'nltk'],
    noarchive=False,
    upx_exclude=['Qt6', 'vcruntime', 'python311', 'sqlcipher3', 'PySide6'],
    optimize=2,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Solid',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    console=True,
    disable_windowed_traceback=True,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/app_icon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=True,
    upx=True,
    upx_exclude=['Qt6', 'vcruntime', 'python311', 'sqlcipher3', 'PySide6'],
    name='Solid',
)
